name: yourgoals
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.7
  font_awesome_flutter: ^8.8.1
  flutter_spinkit: ^4.1.2+1






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  analyzer: 0.38.2
  build_runner:
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  
flutter_launcher_name:
  name: "My Goals"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Caveat
      fonts:
        - asset: fonts/caveat-regular.ttf
    - family: Pixel
      fonts:
        - asset: fonts/pixelmix.ttf
    - family: Caveat
      fonts:
        - asset: fonts/caveat-regular.ttf
    - family: Hearts
      fonts:
        - asset: fonts/Chasing.ttf
    - family: Sunshine
      fonts:
        - asset: fonts/Sunshine_Melody.ttf
    

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
